
version: 2

build:
  os: ubuntu-22.04
  tools:
      python: "3.11"

formats:
    - htmlzip

python:
    install:
      - method: pip
        path: .


sphinx:
    builder: html
    configuration: doc/conf.py
    fail_on_warning: false

